name: CI

on:
  push:
    branches:
    - main
    - develop
    - release/*
  pull_request:
    branches: 
    - main
    - develop
    - release/*

  workflow_dispatch:

jobs:
  build-linux:
    name: flutter build linux
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: "3.0.3"
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Set up Java ğŸ”§
      uses: actions/setup-java@v3
      with:
        java-version: 15
        distribution: 'adopt'
    - name: Set up Flutter version ğŸ”§
      uses: ./.github/actions/flutter-action
      with:
        flutter-version: $FLUTTER_VERSION
    - name: Fetch dependencies
      run: |
        flutter pub get
    - name: Run tests
      run: |
        flutter test -r expanded
    - name: Build app
      run: |
        ./scripts/build-android.sh
    - name: Analyze
      run: |
        flutter analyze

  build-macos:
    name: flutter build macos
    runs-on: macos-12
    env:
      FLUTTER_VERSION: "3.0.3"
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Set up Flutter version ğŸ”§
      uses: ./.github/actions/flutter-action
      with:
        flutter-version: $FLUTTER_VERSION
    - name: Fetch dependencies
      run: |
        flutter pub get
    - name: Run tests
      run: |
        flutter test -r expanded
    - name: Run unmocked integration tests
      run: |
        ./scripts/run-unmocked-integration-tests-ios.sh
    - name: Analyze
      run: |
        flutter analyze

