name: release

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  generate-doc-linux:
    name: flutter build linux

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: "3.0.3"
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Set up Java ğŸ”§
      uses: actions/setup-java@v3
      with:
        java-version: 15
        distribution: 'adopt'
    - name: Set up Flutter version ğŸ”§
      uses: subosito/flutter-action@v2.4.0
      with:
        flutter-version: $FLUTTER_VERSION

    - uses: dart-lang/setup-dart@v1.3

    - name: Install dependencies
      run: |
        dart pub get
    - name: Generate dart doc
      run: |
        dart doc .

    - name: Setup GitHub Pages ğŸ› 
      uses: actions/configure-pages@v2

    - name: Upload artifact â¬†ï¸
      uses: actions/upload-pages-artifact@v1
      with:
        path: doc/api

    - name: Deploy to GitHub Pages ğŸš€
      id: deployment
      uses: actions/deploy-pages@v1
